remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Y J R Q Z 7 7 7 :sparkles:_]
description: [A short description ! :heart: :cowboy_hat_face:_ ]
